config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :doses, only: [:destroy]

  mount Attachinary::Engine => "/attachinary"
  root 'cocktails#index'

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_attachment :photo

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, :ingredient, :description, presence: true
  validates :cocktail, uniqueness: { scope: [:ingredient] }
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true

  before_destroy :check_for_cocktails

  private

  def check_for_cocktails
    if cocktails.count > 0
      errors.add_to_base("cannot delete an ingredient while cocktails include it")
      return false
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :cocktail

  validates :comment, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @ingredients = Ingredient.where.not(id: @cocktail.doses.map(&:ingredient_id))
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :ingredient_id)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    cocktail = Cocktail.find(params[:cocktail_id])
    puts params
    ingredient = Ingredient.find(params[:dose][:ingredient_id])
    @dose = Dose.new(dose_params)
    @dose.ingredient = ingredient
    @dose.cocktail = cocktail
    if @dose.save
      redirect_to cocktail, notice: 'Ingredient successfully added'
    else
      redirect_to cocktail, notice: 'Error while adding the ingredient'
    end
  end

  def destroy
    dose = Dose.find(params[:id])
    cocktail = dose.cocktail
    dose.destroy
    redirect_to cocktail
  end

  private

  def dose_params
    params.require(:dose).permit(:description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    cocktail = Cocktail.find(params[:cocktail_id])
    review = cocktail.reviews.build(review_params)
    review.save
    redirect_to cocktail
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cocktail.photo? ? '''http://res.cloudinary.com/nephaest/image/upload/' + cocktail.photo.path : 'http://placehold.it/400x250' %>);">
          <div class="card-description">
            <h3><%= cocktail.name %></h3>
          </div>
          <%= link_to '', cocktail, class: 'card-link' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <col-xs-12 class="col-sm-6 col-sm-offset-3 padded">
      <%= simple_form_for @cocktail do |f| %>
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <%= f.input :name %>
          </div>
          <div class="col-xs-12 col-sm-6">
            <%= f.input :photo, as: :attachinary %>
          </div>
          <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <div class="text-center">
              <%= f.submit %>
            </div>
          </div>
        </div>
      <% end %>
    </col-xs-12>
  </div>
</div>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2 class="text-center"><%= @cocktail.name %></h2>
  <br>

  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <!-- display & upload a photo -->
      <% if @cocktail.photo? %>
        <%= cl_image_tag @cocktail.photo.path, crop: :fill, class: 'img-responsive' %>
      <% end %>

      <h3>Ingredients <%= icon 'plus', id: 'add-dose' %></h3>

      <div class="">
        <div id="new-dose-form" style="display: none">
          <%= simple_form_for [@cocktail, @dose] do |f| %>
            <%= f.input :description %>
            <%= f.input :ingredient_id, collection: @ingredients %>
            <%= f.submit 'Add' %>
          <% end %>
        </div>
      </div>
      <br>
      <ul class="list-unstyled">
        <% @cocktail.doses.each do |dose| %>
          <li>
            <%= link_to icon('trash-o'), dose_path(dose), method: :delete, data: { confirm: 'Are you sure?' } %> <%= dose.ingredient.name %> (<%= dose.description %>)
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-xs-12 col-sm-6">
      <h3>Reviews</h3>
      <div class="row">
        <div id="new-review-form">
          <%= simple_form_for [@cocktail, @review] do |f| %>
            <div class="col-xs-12 col-md-6">
              <%= f.input :rating, collection: (0..5).to_a %>
            </div>
            <div class="col-xs-12 col-md-6">
              <%= f.input :comment %>
            </div>
            <div class="col-xs-12">
              <%= f.submit 'Add' %>
            </div>
          <% end %>
        </div>
      </div>
      <br>
      <ul class="list-unstyled">
        <% @cocktail.reviews.each do |review| %>
          <li>
            <% (1..5).each do |glass| %>
              <%= icon 'glass', class: glass <= review.rating ? 'glass-enabled' : 'glass-disabled' %>
            <% end %>
            <p><%= review.comment %></p>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mrs. Cocktail</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <div class="wrapper">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= cloudinary_js_config %>
</body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to '/', class: 'navbar-wagon-brand' do %>
    <%= image_tag "cocktail-glass.png" %>
  <% end %>
  <h2>Mrs. Cocktail</h2>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right">
    <!-- Button (call-to-action) -->
    <%= link_to icon('plus'), new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</div>